#!/bin/sh

CPP="g++"
EXTRA_FLAGS="-Wno-write-strings -DSIM_SLOW=1 -Wall"

if [[ $1 == "all" ]]; then
    $CPP src/external_libs.cpp -Iinclude -I/usr/local/include/SDL2 -c -o external.o -g $EXTRA_FLAGS
fi

$CPP src/main.cpp external.o \
    -Iinclude \
    -I/usr/local/include/SDL2 \
    -ldl \
    -lSDL2 \
    -lm \
    -L/usr/local/lib \
    -pthread \
    -o behavior \
    -g \
    $EXTRA_FLAGS \



